version: "3.5"

services:
  # PostgreSQL 15.3 Database (mimics Aurora PostgreSQL)
  postgres:
    image: postgres:15.3
    container_name: temporal-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - temporal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10

  # Database Setup (mimics our Lambda function)
  temporal-db-setup:
    image: temporalio/admin-tools:1.28
    container_name: temporal-db-setup
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
    volumes:
      - ./docker/setup-schema-postgres.sh:/setup-schema-postgres.sh
    networks:
      - temporal-network
    command: ["/bin/bash", "/setup-schema-postgres.sh"]

  # Temporal Server (using manual setup)
  temporal:
    image: temporalio/server:1.28
    container_name: temporal
    depends_on:
      temporal-db-setup:
        condition: service_completed_successfully
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network
    ports:
      - "7233:7233"

  # Temporal Admin Tools
  temporal-admin-tools:
    image: temporalio/admin-tools:1.28
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
    ports:
      - "8080:8080"

  # Nginx (mimics ALB for local development)
  nginx:
    image: nginx:alpine
    container_name: temporal-nginx
    depends_on:
      - temporal-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - temporal-network

volumes:
  postgres_data:

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
